services:
  mongo:
    image: mongo:5.0
    container_name: mongo-db-SAES3
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mdp

volumes:
  mongo_data: